"""
Django settings for container_management project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t*#sdxn_w+20h0xql^=n&g-2z&am8k8b0o*apf52io3tac%5!m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','192.168.3.5']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'management',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'container_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'management' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 仪表盘统计数据，用于 simpleui 首页图表
                'management.dashboard_context.dashboard_stats',
            ],
        },
    },
]

WSGI_APPLICATION = 'container_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'box_management',
        'USER': 'root',
        'PASSWORD': 'iamshp0228',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# 登录配置 - 使用自定义登录页面
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/login/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'management' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# SimpleUI 配置：首页重命名为“仪表盘”，并为常用菜单配置图标
SIMPLEUI_CONFIG = {
    # 首页标题
    'home_title': '仪表盘',
    # 追加自定义菜单项，但保留原有系统/模型菜单
    'menus': [
        {
            'name': '聚合搜索',
            'icon': 'fa fa-search',
            'url': '/admin/search/',
        },
    ],
    'system_keep': True,

}

# 兼容旧写法，部分 simpleui 版本读取 SIMPLEUI_HOME_TITLE
SIMPLEUI_HOME_TITLE = '仪表盘'
# 指定 simpleui 首页 iframe 指向自定义仪表盘视图，确保在 /admin/ 里直接嵌入仪表盘
SIMPLEUI_HOME_PAGE = '/admin/dashboard/'

# 左侧菜单和首页卡片图标映射（键为菜单显示名，一般是 verbose_name_plural）
SIMPLEUI_ICON = {
    '作业任务': 'fa fa-tasks',
    '堆场区': 'fa fa-th-large',
    '堆场堆栈': 'fa fa-layer-group',
    '箱位': 'fa fa-border-all',
    '泊位': 'fa fa-anchor',
    '港口': 'fa fa-ship',
    '船舶': 'fa fa-ship',
    '船舶访问': 'fa fa-route',
    '订舱单': 'fa fa-file-alt',
    '集装箱': 'fa fa-box',
    '集装箱类型字典': 'fa fa-boxes',
    '用户': 'fa fa-user',
    '相关方': 'fa fa-users',
    '权限': 'fa fa-key',
    '用户权限': 'fa fa-user-shield',
}
