# Generated by Django 5.2.8 on 2025-12-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerTypeDict',
            fields=[
                ('type_code', models.CharField(db_column='Type_Code', max_length=4, primary_key=True, serialize=False, verbose_name='ISO类型代码')),
                ('nominal_size', models.IntegerField(db_column='Nominal_Size', verbose_name='名义尺寸')),
                ('group_code', models.CharField(db_column='Group_Code', max_length=4, verbose_name='组代码')),
                ('standard_tare_kg', models.DecimalField(blank=True, db_column='Standard_Tare_KG', decimal_places=2, max_digits=8, null=True, verbose_name='标准皮重')),
            ],
            options={
                'verbose_name': '集装箱类型字典',
                'verbose_name_plural': '集装箱类型字典',
                'db_table': 'Container_Type_Dict',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.AutoField(db_column='Party_ID', primary_key=True, serialize=False)),
                ('party_name', models.CharField(db_column='Party_Name', max_length=255, unique=True, verbose_name='名称')),
                ('party_type', models.CharField(choices=[('COMPANY', '公司'), ('PERSON', '个人')], db_column='Party_Type', max_length=20, verbose_name='类型')),
                ('address_line_1', models.CharField(blank=True, db_column='Address_Line_1', max_length=255, null=True, verbose_name='地址')),
                ('city', models.CharField(blank=True, db_column='City', max_length=100, null=True, verbose_name='城市')),
                ('country', models.CharField(blank=True, db_column='Country', max_length=2, null=True, verbose_name='国家代码')),
                ('contact_person', models.CharField(blank=True, db_column='Contact_Person', max_length=100, null=True, verbose_name='联系人')),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=255, null=True, verbose_name='电子邮件')),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True, verbose_name='电话')),
                ('scac_code', models.CharField(blank=True, db_column='SCAC_Code', max_length=10, null=True, verbose_name='承运人代码')),
            ],
            options={
                'verbose_name': '相关方',
                'verbose_name_plural': '相关方',
                'db_table': 'Party',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('permission_id', models.AutoField(db_column='Permission_ID', primary_key=True, serialize=False)),
                ('permission_name', models.CharField(db_column='Permission_Name', max_length=100, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='PortMaster',
            fields=[
                ('port_id', models.AutoField(db_column='Port_ID', primary_key=True, serialize=False)),
                ('port_name', models.CharField(db_column='Port_Name', max_length=100, verbose_name='名称')),
                ('port_code', models.CharField(db_column='Port_Code', max_length=5, unique=True, verbose_name='代码')),
                ('country', models.CharField(db_column='Country', max_length=2, verbose_name='国家代码')),
            ],
            options={
                'verbose_name': '港口',
                'verbose_name_plural': '港口',
                'db_table': 'Port_Master',
            },
        ),
        migrations.CreateModel(
            name='YardBlock',
            fields=[
                ('block_id', models.AutoField(db_column='Block_ID', primary_key=True, serialize=False)),
                ('block_name', models.CharField(db_column='Block_Name', max_length=50, unique=True, verbose_name='名称')),
                ('block_type', models.CharField(choices=[('Standard', '标准'), ('Cold', '冷藏'), ('Open', '露天')], db_column='Block_Type', default='Standard', max_length=20, verbose_name='类型')),
            ],
            options={
                'verbose_name': '堆场区',
                'verbose_name_plural': '堆场区',
                'db_table': 'Yard_Block',
            },
        ),
        migrations.CreateModel(
            name='ContainerMaster',
            fields=[
                ('container_master_id', models.AutoField(db_column='Container_Master_ID', primary_key=True, serialize=False)),
                ('container_number', models.CharField(db_column='Container_Number', max_length=11, unique=True, verbose_name='箱号')),
                ('current_status', models.CharField(blank=True, choices=[('InYard', '在堆场'), ('OnVessel', '在船上'), ('GateOut', '已出闸')], db_column='Current_Status', max_length=20, null=True, verbose_name='当前状态')),
                ('type_code', models.ForeignKey(db_column='Type_Code', on_delete=django.db.models.deletion.PROTECT, to='management.containertypedict', verbose_name='类型代码')),
                ('owner_party_id', models.ForeignKey(blank=True, db_column='Owner_Party_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.party', verbose_name='箱主')),
            ],
            options={
                'verbose_name': '集装箱',
                'verbose_name_plural': '集装箱',
                'db_table': 'Container_Master',
            },
        ),
        migrations.CreateModel(
            name='Berth',
            fields=[
                ('berth_id', models.AutoField(db_column='Berth_ID', primary_key=True, serialize=False)),
                ('berth_name', models.CharField(db_column='Berth_Name', max_length=50, verbose_name='泊位名称')),
                ('length_meters', models.DecimalField(blank=True, db_column='Length_Meters', decimal_places=2, max_digits=6, null=True, verbose_name='泊位长度(米)')),
                ('depth_meters', models.DecimalField(blank=True, db_column='Depth_Meters', decimal_places=2, max_digits=5, null=True, verbose_name='泊位水深(米)')),
                ('max_vessel_loa', models.DecimalField(blank=True, db_column='Max_Vessel_LOA', decimal_places=2, max_digits=6, null=True, verbose_name='最大容纳船长')),
                ('port_id', models.ForeignKey(db_column='Port_ID', on_delete=django.db.models.deletion.CASCADE, to='management.portmaster', verbose_name='所属港口')),
            ],
            options={
                'verbose_name': '泊位',
                'verbose_name_plural': '泊位',
                'db_table': 'Berth',
                'unique_together': {('port_id', 'berth_name')},
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_column='User_ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=100, unique=True, verbose_name='用户名')),
                ('hashed_password', models.BinaryField(db_column='Hashed_Password', max_length=256, verbose_name='密码')),
                ('full_name', models.CharField(blank=True, db_column='Full_Name', max_length=100, null=True, verbose_name='全名')),
                ('email', models.EmailField(db_column='Email', max_length=255, unique=True, verbose_name='电子邮件')),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True, verbose_name='是否激活')),
                ('party_id', models.ForeignKey(blank=True, db_column='Party_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.party', verbose_name='关联相关方')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='VesselMaster',
            fields=[
                ('vessel_id', models.AutoField(db_column='Vessel_ID', primary_key=True, serialize=False)),
                ('vessel_name', models.CharField(db_column='Vessel_Name', max_length=100, verbose_name='船名')),
                ('imo_number', models.CharField(db_column='IMO_Number', max_length=7, unique=True, verbose_name='IMO编号')),
                ('flag_country', models.CharField(blank=True, db_column='Flag_Country', max_length=2, null=True, verbose_name='船旗国')),
                ('carrier_party_id', models.ForeignKey(blank=True, db_column='Carrier_Party_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.party', verbose_name='承运人')),
            ],
            options={
                'verbose_name': '船舶',
                'verbose_name_plural': '船舶',
                'db_table': 'Vessel_Master',
            },
        ),
        migrations.CreateModel(
            name='VesselVisit',
            fields=[
                ('vessel_visit_id', models.AutoField(db_column='Vessel_Visit_ID', primary_key=True, serialize=False)),
                ('voyage_number_in', models.CharField(db_column='Voyage_Number_In', max_length=20, verbose_name='进口航次')),
                ('voyage_number_out', models.CharField(db_column='Voyage_Number_Out', max_length=20, verbose_name='出口航次')),
                ('ata', models.DateTimeField(blank=True, db_column='ATA', null=True, verbose_name='实际到港时间')),
                ('atd', models.DateTimeField(blank=True, db_column='ATD', null=True, verbose_name='实际离港时间')),
                ('status', models.CharField(choices=[('Approaching', '接近中'), ('AtBerth', '靠泊'), ('Departing', '离港中'), ('Completed', '已完成')], db_column='Status', default='Approaching', max_length=20, verbose_name='状态')),
                ('berth_id', models.ForeignKey(blank=True, db_column='Berth_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.berth', verbose_name='泊位')),
                ('port_id', models.ForeignKey(db_column='Port_ID', on_delete=django.db.models.deletion.CASCADE, to='management.portmaster', verbose_name='挂靠港口')),
                ('vessel_id', models.ForeignKey(db_column='Vessel_ID', on_delete=django.db.models.deletion.CASCADE, to='management.vesselmaster', verbose_name='船舶')),
            ],
            options={
                'verbose_name': '船舶访问',
                'verbose_name_plural': '船舶访问',
                'db_table': 'Vessel_Visit',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(db_column='Booking_ID', primary_key=True, serialize=False)),
                ('booking_number', models.CharField(db_column='Booking_Number', max_length=50, unique=True, verbose_name='订舱号')),
                ('status', models.CharField(choices=[('Draft', '草稿'), ('Confirmed', '已确认'), ('Cancelled', '已取消')], db_column='Status', default='Draft', max_length=20, verbose_name='状态')),
                ('consignee_party_id', models.ForeignKey(blank=True, db_column='Consignee_Party_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignee_bookings', to='management.party', verbose_name='收货人')),
                ('payer_party_id', models.ForeignKey(blank=True, db_column='Payer_Party_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payer_bookings', to='management.party', verbose_name='付费方')),
                ('shipper_party_id', models.ForeignKey(blank=True, db_column='Shipper_Party_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipper_bookings', to='management.party', verbose_name='发货人')),
                ('voyage_id', models.ForeignKey(blank=True, db_column='Voyage_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.vesselvisit', verbose_name='航次')),
            ],
            options={
                'verbose_name': '订舱单',
                'verbose_name_plural': '订舱单',
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='YardSlot',
            fields=[
                ('slot_id', models.AutoField(db_column='Slot_ID', primary_key=True, serialize=False)),
                ('tier_number', models.IntegerField(db_column='Tier_Number', verbose_name='层号')),
                ('slot_coordinates', models.CharField(db_column='Slot_Coordinates', max_length=50, unique=True, verbose_name='坐标')),
                ('slot_status', models.CharField(db_column='Slot_Status', default='Available', max_length=20, verbose_name='状态')),
                ('current_container_id', models.OneToOneField(blank=True, db_column='Current_Container_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.containermaster', verbose_name='当前集装箱')),
            ],
            options={
                'verbose_name': '箱位',
                'verbose_name_plural': '箱位',
                'db_table': 'Yard_Slot',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(db_column='Task_ID', primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('Load', '装船'), ('Discharge', '卸船'), ('Move', '移箱'), ('GateIn', '进闸'), ('GateOut', '出闸')], db_column='Task_Type', max_length=30, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('Pending', '待处理'), ('InProgress', '进行中'), ('Completed', '已完成'), ('Cancelled', '已取消')], db_column='Status', default='Pending', max_length=20, verbose_name='状态')),
                ('priority', models.IntegerField(db_column='Priority', default=100, verbose_name='优先级')),
                ('movement_timestamp', models.DateTimeField(blank=True, db_column='Movement_Timestamp', null=True, verbose_name='实际移动时间戳')),
                ('container_master_id', models.ForeignKey(db_column='Container_Master_ID', on_delete=django.db.models.deletion.CASCADE, to='management.containermaster', verbose_name='集装箱')),
                ('actual_executor_id', models.ForeignKey(blank=True, db_column='Actual_Executor_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_tasks', to='management.users', verbose_name='实际执行人')),
                ('assigned_user_id', models.ForeignKey(blank=True, db_column='Assigned_User_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='management.users', verbose_name='指派给')),
                ('created_by_user_id', models.ForeignKey(db_column='Created_By_User_ID', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='management.users', verbose_name='创建人')),
                ('vessel_visit_id', models.ForeignKey(blank=True, db_column='Vessel_Visit_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.vesselvisit', verbose_name='船舶访问')),
                ('from_slot_id', models.ForeignKey(db_column='From_Slot_ID', on_delete=django.db.models.deletion.CASCADE, related_name='tasks_from', to='management.yardslot', verbose_name='起始箱位')),
                ('to_slot_id', models.ForeignKey(db_column='To_Slot_ID', on_delete=django.db.models.deletion.CASCADE, related_name='tasks_to', to='management.yardslot', verbose_name='目标箱位')),
            ],
            options={
                'verbose_name': '作业任务',
                'verbose_name_plural': '作业任务',
                'db_table': 'Task',
            },
        ),
        migrations.CreateModel(
            name='YardStack',
            fields=[
                ('stack_id', models.AutoField(db_column='Stack_ID', primary_key=True, serialize=False)),
                ('bay_number', models.IntegerField(db_column='Bay_Number', verbose_name='贝位号')),
                ('row_number', models.IntegerField(db_column='Row_Number', verbose_name='排号')),
                ('block_id', models.ForeignKey(db_column='Block_ID', on_delete=django.db.models.deletion.CASCADE, to='management.yardblock', verbose_name='所属堆场区')),
            ],
            options={
                'verbose_name': '堆场堆栈',
                'verbose_name_plural': '堆场堆栈',
                'db_table': 'Yard_Stack',
                'unique_together': {('block_id', 'bay_number', 'row_number')},
            },
        ),
        migrations.AddField(
            model_name='yardslot',
            name='stack_id',
            field=models.ForeignKey(db_column='Stack_ID', on_delete=django.db.models.deletion.CASCADE, to='management.yardstack', verbose_name='所属堆栈'),
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.ForeignKey(db_column='Permission_ID', on_delete=django.db.models.deletion.CASCADE, to='management.permissions', verbose_name='权限')),
                ('user_id', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, to='management.users', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户权限',
                'verbose_name_plural': '用户权限',
                'db_table': 'User_Permissions',
                'unique_together': {('user_id', 'permission_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='yardslot',
            unique_together={('stack_id', 'tier_number')},
        ),
    ]
