# Generated by Django 5.2.8 on 2025-12-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardblock',
            name='block_type',
            field=models.CharField(choices=[('Standard', '标准'), ('Reefer', '冷藏'), ('Temporary', '临时'), ('Heavy', '重载'), ('Bulk', '散货')], db_column='Block_Type', default='Standard', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='yardslot',
            name='slot_status',
            field=models.CharField(choices=[('Available', '可用'), ('Occupied', '占用'), ('Reserved', '预留'), ('Maintenance', '维护')], db_column='Slot_Status', default='Available', max_length=20, verbose_name='状态'),
        ),
    ]
